In [1]:
import numpy as np

## Dot Product

In [2]:
a1 = np.random.randint(5, size=(3,3))
a2 = np.random.randint(10, size=(3,3))

In [3]:
a1

array([[1, 4, 1],
       [1, 1, 0],
       [2, 0, 2]])

In [4]:
a2

array([[0, 2, 2],
       [4, 6, 1],
       [2, 0, 9]])

In [5]:
a1.shape, a2.shape

((3, 3), (3, 3))

In [6]:
a1.dot(a2)

array([[18, 26, 15],
       [ 4,  8,  3],
       [ 4,  4, 22]])

In [7]:
a3 = np.random.randint(5, size=(3,2))

In [8]:
a3

array([[0, 2],
       [2, 0],
       [2, 1]])

In [9]:
a1.dot(a3)

array([[10,  3],
       [ 2,  2],
       [ 4,  6]])

In [10]:
a4 = np.random.randint(5, size=(2,3))
a4

array([[3, 4, 2],
       [0, 1, 2]])

In [11]:
a1

array([[1, 4, 1],
       [1, 1, 0],
       [2, 0, 2]])

In [12]:
a1.shape, a4.shape

((3, 3), (2, 3))

In [13]:
a1.dot(a4)

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

NOTES:
    - Main take away is if shape of a1 is (3,2) then a2 should be having (2,3)
    - The colum value of first matrix and row of second matrix should be equal. Then only we can do a dot product
    - The resultant matrix will be in the form (3,3) [Outer numbers of both matrices]