## Exercise: numpy pandas dot

In [1]:
import pandas as pd
import numpy as np

In [2]:
sales_array = np.array([[2,7,1],
                        [9,4,16],
                        [11,14,18],
                        [13,13,16],
                        [15,18,9]])
sales_array

array([[ 2,  7,  1],
       [ 9,  4, 16],
       [11, 14, 18],
       [13, 13, 16],
       [15, 18,  9]])

In [3]:
sales_array.shape

(5, 3)

In [5]:
sales_data = pd.DataFrame(sales_array,
                          index=["Mon","Tues","Wed","Thrus","Fri"],
                          columns=["Almond butter","Peanut butter","Cachew butter"])
sales_data

Almond butter  Peanut butter  Cachew butter
Mon                2              7              1
Tues               9              4             16
Wed               11             14             18
Thrus             13             13             16
Fri               15             18              9

In [6]:
price_array = np.array([10,8,12])
price_array

array([10,  8, 12])

In [8]:
price_array.shape

(3,)

In [9]:
price_data = pd.DataFrame(price_array.reshape(1,3),
                          index=["Price"],
                          columns=["Almond butter","Peanut butter","Cachew butter"])
price_data

Almond butter  Peanut butter  Cachew butter
Price             10              8             12

In [14]:
price_array.shape, sales_array.shape

((3,), (5, 3))

In [15]:
total_sales = price_array.dot(sales_array.T) # We transposed it, bcoz matrices were not aligned
total_sales

array([ 88, 314, 438, 426, 402])

In [17]:
sales_data['Total ($)'] = total_sales

In [18]:
sales_data

Almond butter  Peanut butter  Cachew butter  Total ($)
Mon                2              7              1         88
Tues               9              4             16        314
Wed               11             14             18        438
Thrus             13             13             16        426
Fri               15             18              9        402