In [1]:
import numpy as np

## Creating arrays

In [2]:
a1 = np.array([2,4,5,2])
a1

array([2, 4, 5, 2])

In [9]:
a1.shape

(4,)

In [3]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[2,3,4],
               [5,3,2]])
a2

array([[2, 3, 4],
       [5, 3, 2]])

In [10]:
a2.shape

(2, 3)

In [6]:
type(a2)

numpy.ndarray

In [8]:
a3 = np.array([[[2,3,4],
                [1,2,3]],
               [[3,4,5],
                [1,2,3]],
               [[4,2,1],
                [7,2,1]]])
a3

array([[[2, 3, 4],
        [1, 2, 3]],

       [[3, 4, 5],
        [1, 2, 3]],

       [[4, 2, 1],
        [7, 2, 1]]])

In [11]:
a3.shape

(3, 2, 3)

In [12]:
type(a3)

numpy.ndarray

## Finding standard deviation and variance

In [13]:
data = np.arange(1,10)
data

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
data.shape

(9,)

In [20]:
data = data.reshape((3,3))
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
data.shape

(3, 3)

In [21]:
np.var(data)

6.666666666666667

In [22]:
np.std(data)

2.581988897471611

## Creating arrays using different methods

In [42]:
np.random.seed(2)
method_1 = np.random.randint(6, size=(5,6))
method_1

array([[0, 5, 0, 3, 2, 3],
       [0, 2, 1, 3, 5, 2],
       [4, 4, 4, 5, 3, 4],
       [2, 3, 3, 2, 1, 2],
       [4, 3, 5, 0, 4, 3]])

In [27]:
method_2 = np.random.random(size=(3,4))
method_2

array([[0.5597128 , 0.91318665, 0.35831017, 0.22222065],
       [0.47305802, 0.04651377, 0.71309777, 0.48809598],
       [0.07512131, 0.40457325, 0.63168831, 0.47879273]])

In [28]:
method_3 = np.random.randn(10)
method_3

array([-0.39193478, -0.74554393, -0.17460824,  0.72150833,  0.77995198,
       -1.8794328 , -1.20312645,  1.30818635,  0.41877854, -1.04963426])

In [29]:
method_3.shape

(10,)

In [34]:
method_4 = np.arange(1,12,2)
method_4

array([ 1,  3,  5,  7,  9, 11])

In [38]:
method_4 = method_4.reshape(3,2)
method_4

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

## Arithmetic Operations

In [45]:
array_1 = np.array([2,4,3])

In [64]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [65]:
array_1.shape, ones.shape

((3,), (3,))

In [66]:
array_1 + ones

array([3., 5., 4.])

In [68]:
# Numpy .add() do the addition element wise
np.add(array_1,ones)

array([3., 5., 4.])

In [69]:
np.subtract(array_1,ones)

array([1., 3., 2.])

In [70]:
np.multiply(array_1,ones)

array([2., 4., 3.])

In [71]:
np.divide(array_1,ones)

array([2., 4., 3.])

In [72]:
np.mod(array_1,ones)

array([0., 0., 0.])

### Samples performing on different shapes

In [73]:
array_2 = np.random.randint(5, size=(3,3))
array_2

array([[2, 0, 2],
       [3, 3, 0],
       [0, 3, 3]])

In [74]:
array_1.shape, array_2.shape

((3,), (3, 3))

In [75]:
np.add(array_1,array_2)

array([[4, 4, 5],
       [5, 7, 3],
       [2, 7, 6]])

In [78]:
array_3 = np.random.randint(5, size=(5,5))
array_3

array([[0, 0, 2, 3, 1],
       [2, 3, 4, 3, 3],
       [1, 4, 2, 3, 0],
       [0, 2, 4, 4, 3],
       [2, 1, 1, 1, 2]])

In [79]:
np.add(array_1,array_3)

ValueError: operands could not be broadcast together with shapes (3,) (5,5) 

In [102]:
array_1.shape, array_3.shape

((3,), (5, 5))

In [89]:
test = np.random.randint(5, size=(4,6))
test

array([[0, 3, 1, 4, 1, 2],
       [1, 2, 3, 1, 3, 2],
       [4, 3, 2, 4, 4, 2],
       [3, 2, 4, 2, 2, 3]])

In [100]:
test1 = np.random.randint(10, size=(4,6))
test1

array([[8, 8, 2, 6, 0, 6],
       [0, 4, 3, 3, 7, 0],
       [9, 2, 2, 3, 5, 6],
       [0, 6, 0, 3, 7, 3]])

In [101]:
np.multiply(test,test1)

array([[ 0, 24,  2, 24,  0, 12],
       [ 0,  8,  9,  3, 21,  0],
       [36,  6,  4, 12, 20, 12],
       [ 0, 12,  0,  6, 14,  9]])

NOTES:
    - Arithmetic operations can be performed if the colums size is same, no matter what is the row size
    - `np.add()` performs the element wise addition
    - We can do `array_3.reshape(row, colums)` to tackle this situation